services:
  vllm:
    image: ghcr.io/red-hat-ai-dev/vllm-zero-to-hero:cuda
    ports:
      - "8000:8000"
    ipc: host
    volumes:
      - vllm-models:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  vllm-models:
