services:
  vllm:
    image: ghcr.io/red-hat-ai-dev/vllm-zero-to-hero:xpu
    ports:
      - "8000:8000"
    ipc: host
    privileged: true
    volumes:
      - vllm-models:/root/.cache/huggingface
      - /dev/dri/by-path:/dev/dri/by-path
    devices:
      - /dev/dri:/dev/dri

volumes:
  vllm-models:
